#pragma once

// an external backend might generate file within its code tree
// and check all the source files within the tree with clang-format.
// so, disable it since the backend might have a different config.
// clang-format off

// Autogenerated file by gen_backend_stubs.py. Do not edit directly!

#include <ATen/Tensor.h>


#include <ATen/ops/div_meta.h>
#include <ATen/ops/mul_meta.h>
#include <ATen/ops/sub_meta.h>
namespace at {
namespace priv1 {
namespace native {

struct PrivateUse1NativeFunctions {

static at::Tensor & div_out(const at::Tensor & self, const at::Tensor & other, at::Tensor & out);
struct structured_mul_out : public at::meta::structured_mul_Tensor {
void impl(const at::Tensor & self, const at::Tensor & other, const at::Tensor & out);
};
struct structured_sub_out : public at::meta::structured_sub_Tensor {
// Alias to the base meta class for easy access to native meta logic
using base = at::meta::structured_sub_Tensor;
void meta(const at::Tensor & self, const at::Tensor & other, const at::Scalar & alpha);
void impl(const at::Tensor & self, const at::Tensor & other, const at::Scalar & alpha, const at::Tensor & out);
};

};
} // namespace native
} // namespace priv1
} // namespace at
