#pragma once

// an external backend might generate file within its code tree
// and check all the source files within the tree with clang-format.
// so, disable it since the backend might have a different config.
// clang-format off

// Autogenerated file by gen_backend_stubs.py. Do not edit directly!

#include <ATen/Tensor.h>


#include <ATen/ops/div_meta.h>
namespace priv1 {
namespace native {

struct PrivateUse1NativeFunctions {

static at::Tensor & div_out(const at::Tensor & self, const at::Tensor & other, at::Tensor & out);
static at::Tensor mul(const at::Tensor & self, const at::Tensor & other);
static at::Tensor sub(const at::Tensor & self, const at::Tensor & other, const at::Scalar & alpha);

};
} // namespace native
} // namespace priv1
