// an external backend might generate file within its code tree
// and check all the source files within the tree with clang-format.
// so, disable it since the backend might have a different config.
// clang-format off

// NOTE: This condition is true for all PyTorch internal libraries, it
//       just excludes external projects such as torch_xla which
//       reuse some of the PyTorch codegen machinery.
#if defined(CAFFE2_BUILD_MAIN_LIB)        || \
    defined(TORCH_CUDA_BUILD_MAIN_LIB)    || \
    defined(TORCH_HIP_BUILD_MAIN_LIB)     || \
    defined(TORCH_XPU_BUILD_MAIN_LIB)
#define TORCH_ASSERT_ONLY_METHOD_OPERATORS
#endif

// @generated by torchgen/gen_backend_stubs.py from RegisterDispatchKey.cpp

#include <c10/core/TensorImpl.h>
#include <c10/core/Allocator.h>
#include <ATen/DeviceGuard.h>
#include <ATen/NamedTensorUtils.h>
#include <ATen/Utils.h>
#include <ATen/WrapDimUtils.h>
#include <ATen/Dispatch.h>
#include <c10/util/ExclusivelyOwned.h>
#include <c10/util/Half.h>
#include <c10/core/UndefinedTensorImpl.h>
#include <optional>
#include <ATen/Tensor.h>
#include <ATen/native/Resize.h>

#include <cstddef>
#include <functional>
#include <memory>
#include <utility>

#include <ATen/Config.h>
#include <ATen/core/op_registration/adaption.h>
#include <torch/library.h>

#include "./existing_generated/PrivateUse1NativeFunctions.h"
#include <ATen/NativeFunctions.h>
#include <ATen/Functions.h>
#include <c10/macros/Macros.h>
#include <ATen/Functions.h>

namespace at {
namespace {
C10_DIAGNOSTIC_PUSH_AND_IGNORED_IF_DEFINED("-Wunused-function")

Tensor create_out(IntArrayRef sizes, IntArrayRef strides, const TensorOptions &options) {
  if (strides.empty()) {
      return at::empty(sizes, options);
  } else {
      return at::empty_strided(sizes, strides, options);
  }
}

void resize_out(const Tensor &out, IntArrayRef sizes, IntArrayRef strides, const TensorOptions &options) {
  TORCH_CHECK(options.dtype() == out.dtype(),
      "Expected out tensor to have dtype ", options.dtype(), ", but got ", out.dtype(), " instead");
  TORCH_CHECK(options.device() == out.device(),
      "Expected out tensor to have device ", options.device(), ", but got ", out.device(), " instead");
  const bool resized = at::native::resize_output(out, sizes);
  // Only restride if a resize occurred; otherwise we ignore the (advisory)
  // strides from the meta function and directly use the output tensor's
  // preexisting strides
  if (resized) {
    if (!strides.empty()) {
      TORCH_INTERNAL_ASSERT(!options.memory_format_opt().has_value());
      // TODO: avoid the redispatch here
      out.as_strided_(sizes, strides);
    } else if (options.memory_format_opt().has_value()) {
      out.unsafeGetTensorImpl()->empty_tensor_restride(*options.memory_format_opt());
    }
  }
}

void check_inplace(const Tensor &self, IntArrayRef sizes, const TensorOptions &options) {
  // These checks are needed on those operators that:
  //   1) don't use 'TensorIterator' (e.g. 'addmm' and 'baddbmm')
  //   2) have particular typing rules (e.g. 'cumsum' and 'cumprod')
  // For other operators (e.g. 'add'), 'TensorIterator' already checks
  // these things separately.
  TORCH_CHECK(options.dtype() == self.dtype(),
      "Bad in-place call: ",
      "input tensor dtype ", self.dtype(), " and output tensor dtype ", options.dtype(), " should match");
  TORCH_CHECK(options.device() == self.device(),
      "Bad in-place call: ",
      "input tensor device ", self.device(), " and output tensor device ", options.device(), " should match");
  TORCH_CHECK(sizes == self.sizes(),
      "Bad in-place call: ",
      "input tensor size ", self.sizes(), " and output tensor size ", sizes, " should match");
}

std::optional<Tensor> maybe_create_proxy(const Tensor &out, IntArrayRef sizes, IntArrayRef strides, const TensorOptions &options) {
  if (out.strides() != strides) {
    return at::empty_strided(sizes, strides, options);
  }
  return std::nullopt;
}
C10_DIAGNOSTIC_POP()
} // namespace
} // namespace at

// See template file RegisterDispatchDefinitions.ini
namespace at {
// NB: TORCH_LIBRARY_IMPL must be in an anonymous namespace to avoid
// ambiguity with conflicting identifiers that may have been defined in
// at namespace already.
namespace {
namespace {
at::Tensor & wrapper_PrivateUse1_out_div_out(const at::Tensor & self, const at::Tensor & other, at::Tensor & out) {
    // No device check
  // DeviceGuard omitted
  return priv1::native::PrivateUse1NativeFunctions::div_out(self, other, out);
}
} // anonymous namespace
namespace {
at::Tensor wrapper_PrivateUse1_Tensor_mul(const at::Tensor & self, const at::Tensor & other) {
    // No device check
  // DeviceGuard omitted
  return priv1::native::PrivateUse1NativeFunctions::mul(self, other);
}
} // anonymous namespace
at::Tensor & wrapper_PrivateUse1_out_mul_out(const at::Tensor & self, const at::Tensor & other, at::Tensor & out) {
  auto wrapper_PrivateUse1_out_mul_out_tmp = wrapper_PrivateUse1_Tensor_mul(self, other);
  at::_copy_from_and_resize(wrapper_PrivateUse1_out_mul_out_tmp, out);
  return out;
}
at::Tensor & wrapper_PrivateUse1_Tensor_mul_(at::Tensor & self, const at::Tensor & other) {
  auto wrapper_PrivateUse1_Tensor_mul__tmp = wrapper_PrivateUse1_Tensor_mul(self, other);
  at::_copy_from(wrapper_PrivateUse1_Tensor_mul__tmp, self);
  return self;
}
namespace {
at::Tensor wrapper_PrivateUse1_Tensor_sub(const at::Tensor & self, const at::Tensor & other, const at::Scalar & alpha) {
    // No device check
  // DeviceGuard omitted
  return priv1::native::PrivateUse1NativeFunctions::sub(self, other, alpha);
}
} // anonymous namespace
at::Tensor & wrapper_PrivateUse1_out_sub_out(const at::Tensor & self, const at::Tensor & other, const at::Scalar & alpha, at::Tensor & out) {
  auto wrapper_PrivateUse1_out_sub_out_tmp = wrapper_PrivateUse1_Tensor_sub(self, other, alpha);
  at::_copy_from_and_resize(wrapper_PrivateUse1_out_sub_out_tmp, out);
  return out;
}
at::Tensor & wrapper_PrivateUse1_Tensor_sub_(at::Tensor & self, const at::Tensor & other, const at::Scalar & alpha) {
  auto wrapper_PrivateUse1_Tensor_sub__tmp = wrapper_PrivateUse1_Tensor_sub(self, other, alpha);
  at::_copy_from(wrapper_PrivateUse1_Tensor_sub__tmp, self);
  return self;
}
TORCH_LIBRARY_IMPL(aten, PrivateUse1, m) {
    m.impl("div.out",
    TORCH_FN(wrapper_PrivateUse1_out_div_out));
    m.impl("mul.Tensor",
    TORCH_FN(wrapper_PrivateUse1_Tensor_mul));
    m.impl("mul.out",
    TORCH_FN(wrapper_PrivateUse1_out_mul_out));
    m.impl("mul_.Tensor",
    TORCH_FN(wrapper_PrivateUse1_Tensor_mul_));
    m.impl("sub.Tensor",
    TORCH_FN(wrapper_PrivateUse1_Tensor_sub));
    m.impl("sub.out",
    TORCH_FN(wrapper_PrivateUse1_out_sub_out));
    m.impl("sub_.Tensor",
    TORCH_FN(wrapper_PrivateUse1_Tensor_sub_));
}
} // anonymous namespace
namespace privateuse1 {
} // namespace privateuse1
} // namespace at
